export const Labels: Record<any, string> = {
  WINTER: "Winter",
  SPRING: "Spring",
  SUMMER: "Summer",
  FALL: "Fall",
  POPULARITY_DESC:"Popularity",
  SCORE_DESC:"Score",
  TV:"TV",
  TV_SHORT: "Shorts",
  MOVIE: "Movie",
  OVA: "OVA",
  ONA: "ONA",
  CURRENT: "Watching",
  COMPLETED: "Finished",
  PLANNING: "Planning",
  DROPPED: "Dropped",
  PAUSED: "Paused",
  REPEATING: "Repeating",
  NOT_YET_AIRED: "Not aired yet",
  RELEASING: "Releasing",
  FINISHED: "Finished",
  NOT_YET_RELEASED: "Not released yet",
  CANCELLED: "Canceled",
} 